# Generated by Django 3.2.5 on 2021-07-28 05:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=35)),
                ('nombrec', models.CharField(max_length=35)),
                ('apellido', models.CharField(max_length=35)),
                ('direccion', models.CharField(max_length=40)),
                ('fecha', models.DateField()),
                ('telefono', models.CharField(max_length=35)),
                ('correo', models.EmailField(max_length=40)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('saldo_pagar', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estado', models.BooleanField()),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_lotificadora.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrel', models.CharField(max_length=35)),
                ('ubicacion', models.CharField(max_length=40)),
                ('dimension', models.CharField(max_length=40)),
                ('cuotas', models.DecimalField(decimal_places=0, max_digits=4)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=12)),
                ('vendido', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=35)),
                ('nombrec', models.CharField(max_length=35)),
                ('apellido', models.CharField(max_length=35)),
                ('direccion', models.CharField(max_length=40)),
                ('fecha', models.DateField()),
                ('telefono', models.CharField(max_length=35)),
                ('correo', models.EmailField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('movimiento', models.CharField(choices=[('1', 'Pago cuota'), ('2', 'Pago a capital')], max_length=1)),
                ('monto', models.FloatField(blank=True, null=True)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destino', to='app_lotificadora.cuenta')),
                ('origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origen', to='app_lotificadora.cuenta')),
            ],
        ),
    ]
