# Generated by Django 3.2.5 on 2021-07-28 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_lotificadora', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pago',
            name='destino',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='direccion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='saldo_pagar',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='lote',
            name='cuotas',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='lote',
            name='precio',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='pago',
            name='origen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_lotificadora.cuenta'),
        ),
    ]
