# Generated by Django 3.2.5 on 2021-07-28 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_lotificadora', '0002_auto_20210728_1713'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='nombrec',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='lote',
            old_name='nombrel',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='sector',
            old_name='nombres',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='vendedor',
            old_name='nombrec',
            new_name='nombre',
        ),
    ]
