# Generated by Django 3.2.5 on 2021-07-30 07:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_lotificadora', '0004_lote_sector'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='user',
        ),
        migrations.RemoveField(
            model_name='lote',
            name='cuotas',
        ),
        migrations.AddField(
            model_name='sector',
            name='Cantidad',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='vendedor',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuotas', models.FloatField(default=0)),
                ('precio_cuota', models.FloatField(default=0)),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_lotificadora.cliente')),
                ('lote', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_lotificadora.lote')),
                ('sector', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_lotificadora.sector')),
                ('vendedor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_lotificadora.vendedor')),
            ],
        ),
    ]
