# Generated by Django 3.2.5 on 2021-07-31 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_lotificadora', '0007_rename_cantidad_sector_cantidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pago',
            name='comentario',
        ),
        migrations.AddField(
            model_name='cliente',
            name='estado',
            field=models.BooleanField(default=1),
        ),
    ]
