# Generated by Django 3.2.5 on 2021-07-31 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_lotificadora', '0008_auto_20210731_0251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contrato',
            name='cliente',
        ),
        migrations.AddField(
            model_name='contrato',
            name='cliente',
            field=models.ManyToManyField(blank=True, to='app_lotificadora.Cliente'),
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='lote',
        ),
        migrations.AddField(
            model_name='contrato',
            name='lote',
            field=models.ManyToManyField(blank=True, to='app_lotificadora.Lote'),
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='sector',
        ),
        migrations.AddField(
            model_name='contrato',
            name='sector',
            field=models.ManyToManyField(blank=True, to='app_lotificadora.Sector'),
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='vendedor',
        ),
        migrations.AddField(
            model_name='contrato',
            name='vendedor',
            field=models.ManyToManyField(blank=True, to='app_lotificadora.Vendedor'),
        ),
    ]
