# Generated by Django 3.2.5 on 2021-07-31 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_lotificadora', '0009_auto_20210731_0401'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contrato',
            name='cliente',
        ),
        migrations.AddField(
            model_name='contrato',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_lotificadora.cliente'),
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='lote',
        ),
        migrations.AddField(
            model_name='contrato',
            name='lote',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_lotificadora.lote'),
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='sector',
        ),
        migrations.AddField(
            model_name='contrato',
            name='sector',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_lotificadora.sector'),
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='vendedor',
        ),
        migrations.AddField(
            model_name='contrato',
            name='vendedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_lotificadora.vendedor'),
        ),
    ]
