# Generated by Django 3.2.5 on 2021-08-01 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_lotificadora', '0011_cliente_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='fecha_ingreso',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='dni',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(max_length=13),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='cuotas',
            field=models.IntegerField(default=0),
        ),
    ]
