# Generated by Django 3.2.5 on 2021-08-01 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_lotificadora', '0012_auto_20210801_0316'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendedor',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vendedor',
            name='fecha_ingreso',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='direccion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='dni',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='telefono',
            field=models.CharField(max_length=13),
        ),
    ]
