# Generated by Django 3.2.5 on 2021-08-02 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_lotificadora', '0013_auto_20210801_0321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contrato',
            name='sector',
        ),
    ]
