# Generated by Django 3.2.3 on 2021-08-03 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_lotificadora', '0014_remove_contrato_sector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lote',
            name='estado',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lote',
            name='precio',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='sector',
            name='cantidad',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
