# Generated by Django 3.2.3 on 2021-08-03 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_lotificadora', '0015_auto_20210803_0134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lote',
            name='dimension',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
