# Generated by Django 3.2.5 on 2021-08-03 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_lotificadora', '0016_alter_lote_dimension'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuenta',
            name='lote',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_lotificadora.lote'),
        ),
    ]
