# Generated by Django 3.2.5 on 2021-08-04 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_lotificadora', '0017_cuenta_lote'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuenta',
            name='contrato',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_lotificadora.contrato'),
        ),
    ]
