# Generated by Django 3.2.5 on 2021-08-04 01:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_lotificadora', '0018_cuenta_contrato'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuenta',
            name='contrato',
        ),
        migrations.AddField(
            model_name='contrato',
            name='cuenta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_lotificadora.cuenta'),
        ),
    ]
